//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeAverages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GradeAverages.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
        ///&quot;GP&quot;;&quot;F&quot;;18;&quot;U&quot;;&quot;GT3&quot;;&quot;A&quot;;4;4;&quot;at_home&quot;;&quot;teacher&quot;;&quot;course&quot;;&quot;mother&quot;;2;2;0;&quot;yes&quot;;&quot;no&quot;;&quot;no&quot;;&quot;no&quot;;&quot;yes&quot;;&quot;yes&quot;;&quot;no&quot;;&quot;no&quot;;4;3;4;1;1;3;6;&quot;5&quot;;&quot;6&quot;;6
        ///&quot;GP&quot;;&quot;F&quot;;17;&quot;U&quot;;&quot;GT3&quot;;&quot;T&quot;;1;1;&quot;at_home&quot;;&quot;other&quot;;&quot;course&quot;;&quot;father&quot;;1;2;0;&quot;no&quot;;&quot;yes&quot;;&quot;no&quot;;&quot;no&quot;;&quot;no&quot;;&quot;yes&quot;;&quot;yes&quot;;&quot;no&quot;;5;3;3;1;1;3;4;&quot;5&quot;;&quot;5&quot;;6
        ///&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string student_mat {
            get {
                return ResourceManager.GetString("student_mat", resourceCulture);
            }
        }
    }
}
